### ISSUE TITLE
Corewar-ui fails linting

### ISSUE THREAD

**Issue by gareththegeek** [corewar/corewar.io#48]
I have excluded `corewar-ui` package from linting for now as it fails linting checks and breaks the CI build.

In order to reintroduce add `js` extension to `package.json` `lint` and `lint:fix` scripts and remove `corewar-ui` folder from `.eslintrc` exclusions.

**Comment by dougajmcdonald** [comment]
Not sure I fully understand thing one.

What linting command fails?

Should I re-introduce? via the steps suggested and fix?

**Comment by dougajmcdonald** [comment]
This is superseded, and no longer relevant
