### ISSUE TITLE
Broken Links in documentation

### ISSUE THREAD

**Issue by robgorham** [corewar/corewar.io#79]
I have found multiple pages with broken links when browsing.  Am I missing something about markdown links and .md files as targets?

### Expected Behavior
Links inside of docs follow to specified anchor

### Actual Behavior
404 response

### Possible Solution
add ``` .md ``` to targets

### Steps to reproduce
1. Browse to [docs/corewar/core.md](https://github.com/corewar/corewar.io/blob/master/docs/corewar/core.md)
2. Click on link ``` loaded ```

This pattern is prevalent in many files.  I have submitted a pull request for one file currently.  I would be willing to pick this up for the others.  In addition, the anchors in [https://github.com/corewar/corewar.io/blob/master/docs/redcode/opcodes.md](https://github.com/corewar/corewar.io/blob/master/docs/redcode/opcodes.md) do not seem to work.

**Comment by gareththegeek** [comment]
This is intended to work when deployed to readthedocs.io
For example, the links are working here without .md extension: https://corewar-docs.readthedocs.io/en/latest/developer/

**Comment by robgorham** [comment]
Thanks for the reply.  If the docs were meant not to be read out of the
github site then I believe I have no issue.
